// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import path from "node:path";
import { defineConfig } from "prisma/config";

function resolveDatabaseUrl(url: string | undefined): string | undefined {
  if (!url) return url;
  if (url.startsWith("file:")) {
    const relativePath = url.slice("file:".length);
    return `file:${path.resolve(process.cwd(), relativePath)}`;
  }
  return url;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: resolveDatabaseUrl(process.env["DATABASE_URL"]),
  },
});
