import type { FormulaProduct, SupplementProduct } from "@/types/nutrition";

/**
 * 预置配方奶粉产品库 (Presets)
 * 涵盖中国市场主流一二三段配方奶粉，包含冲调比例与全量成分表
 */
export const PRESET_FORMULA_PRODUCTS: Omit<FormulaProduct, "id" | "familyId" | "createdAt" | "updatedAt">[] = [
  {
    name: "爱他美卓萃 1段 (0-6个月)",
    brand: "Aptamil/爱他美",
    stage: 1,
    scoopWeightG: 4.3,
    waterPerScoopMl: 30.0,
    reconstitutionRatio: 0.135,
    servingSizeUnit: "per_100g",
    isActive: true,
    notes: "欧洲原装进口，添加天然乳脂与优量益生元组合",
    nutrients: {
      energy_kcal: { amount: 485, unit: "kcal" },
      energy_kj: { amount: 2030, unit: "kJ" },
      protein: { amount: 9.8, unit: "g" },
      fat: { amount: 24.5, unit: "g" },
      carbohydrate: { amount: 55.2, unit: "g" },
      linoleic_acid: { amount: 3400, unit: "mg" },
      alpha_linolenic_acid: { amount: 380, unit: "mg" },
      dha: { amount: 65, unit: "mg" },
      ara: { amount: 65, unit: "mg" },
      vitamin_a: { amount: 420, unit: "mcg RAE" },
      vitamin_d: { amount: 380, unit: "IU" },
      vitamin_e: { amount: 8.5, unit: "mg α-TE" },
      vitamin_k: { amount: 38, unit: "mcg" },
      vitamin_b1: { amount: 0.45, unit: "mg" },
      vitamin_b2: { amount: 0.75, unit: "mg" },
      vitamin_b6: { amount: 0.38, unit: "mg" },
      vitamin_b12: { amount: 1.5, unit: "mcg" },
      vitamin_c: { amount: 65, unit: "mg" },
      folate: { amount: 85, unit: "mcg DFE" },
      niacin: { amount: 3.5, unit: "mg NE" },
      pantothenic_acid: { amount: 2.8, unit: "mg" },
      biotin: { amount: 12, unit: "mcg" },
      choline: { amount: 120, unit: "mg" },
      calcium: { amount: 340, unit: "mg" },
      phosphorus: { amount: 210, unit: "mg" },
      potassium: { amount: 500, unit: "mg" },
      sodium: { amount: 160, unit: "mg" },
      magnesium: { amount: 38, unit: "mg" },
      iron: { amount: 5.2, unit: "mg" },
      zinc: { amount: 3.8, unit: "mg" },
      copper: { amount: 310, unit: "mcg" },
      iodine: { amount: 75, unit: "mcg" },
      selenium: { amount: 14, unit: "mcg" },
      taurine: { amount: 35, unit: "mg" },
      nucleotides: { amount: 22, unit: "mg" },
    },
  },
  {
    name: "爱他美卓萃 2段 (6-12个月)",
    brand: "Aptamil/爱他美",
    stage: 2,
    scoopWeightG: 4.5,
    waterPerScoopMl: 30.0,
    reconstitutionRatio: 0.14,
    servingSizeUnit: "per_100g",
    isActive: true,
    notes: "适合较大婴儿，强化铁与锌",
    nutrients: {
      energy_kcal: { amount: 472, unit: "kcal" },
      energy_kj: { amount: 1975, unit: "kJ" },
      protein: { amount: 12.5, unit: "g" },
      fat: { amount: 21.0, unit: "g" },
      carbohydrate: { amount: 57.5, unit: "g" },
      dha: { amount: 60, unit: "mg" },
      ara: { amount: 60, unit: "mg" },
      vitamin_a: { amount: 450, unit: "mcg RAE" },
      vitamin_d: { amount: 360, unit: "IU" },
      calcium: { amount: 520, unit: "mg" },
      phosphorus: { amount: 310, unit: "mg" },
      iron: { amount: 7.2, unit: "mg" },
      zinc: { amount: 4.2, unit: "mg" },
      vitamin_c: { amount: 60, unit: "mg" },
      vitamin_b1: { amount: 0.5, unit: "mg" },
      vitamin_b2: { amount: 0.8, unit: "mg" },
    },
  },
  {
    name: "爱他美卓萃 3段 (12-36个月)",
    brand: "Aptamil/爱他美",
    stage: 3,
    scoopWeightG: 4.8,
    waterPerScoopMl: 30.0,
    reconstitutionRatio: 0.145,
    servingSizeUnit: "per_100g",
    isActive: true,
    notes: "适合幼儿期，富含钙质与膳食纤维",
    nutrients: {
      energy_kcal: { amount: 460, unit: "kcal" },
      protein: { amount: 14.5, unit: "g" },
      fat: { amount: 19.5, unit: "g" },
      carbohydrate: { amount: 60.0, unit: "g" },
      dha: { amount: 55, unit: "mg" },
      vitamin_a: { amount: 480, unit: "mcg RAE" },
      vitamin_d: { amount: 320, unit: "IU" },
      calcium: { amount: 650, unit: "mg" },
      iron: { amount: 6.8, unit: "mg" },
      zinc: { amount: 3.9, unit: "mg" },
    },
  },
  {
    name: "飞鹤星飞帆 1段 (0-6个月)",
    brand: "飞鹤/Feihe",
    stage: 1,
    scoopWeightG: 4.3,
    waterPerScoopMl: 30.0,
    reconstitutionRatio: 0.135,
    servingSizeUnit: "per_100g",
    isActive: true,
    notes: "中国宝宝体质专属配方，添加OPO结构脂与叶黄素",
    nutrients: {
      energy_kcal: { amount: 510, unit: "kcal" },
      protein: { amount: 10.5, unit: "g" },
      fat: { amount: 26.5, unit: "g" },
      carbohydrate: { amount: 56.0, unit: "g" },
      dha: { amount: 62, unit: "mg" },
      ara: { amount: 75, unit: "mg" },
      vitamin_a: { amount: 440, unit: "mcg RAE" },
      vitamin_d: { amount: 360, unit: "IU" },
      calcium: { amount: 360, unit: "mg" },
      iron: { amount: 5.5, unit: "mg" },
      zinc: { amount: 3.6, unit: "mg" },
      lutein: { amount: 120, unit: "mcg" },
    },
  },
  {
    name: "惠氏启赋蓝钻 1段 (0-6个月)",
    brand: "Wyeth/启赋",
    stage: 1,
    scoopWeightG: 4.3,
    waterPerScoopMl: 30.0,
    reconstitutionRatio: 0.135,
    servingSizeUnit: "per_100g",
    isActive: true,
    notes: "富含GSMO与乳源活性因子",
    nutrients: {
      energy_kcal: { amount: 512, unit: "kcal" },
      protein: { amount: 10.2, unit: "g" },
      fat: { amount: 26.8, unit: "g" },
      carbohydrate: { amount: 57.0, unit: "g" },
      dha: { amount: 65, unit: "mg" },
      ara: { amount: 65, unit: "mg" },
      vitamin_a: { amount: 430, unit: "mcg RAE" },
      vitamin_d: { amount: 350, unit: "IU" },
      calcium: { amount: 350, unit: "mg" },
      iron: { amount: 5.0, unit: "mg" },
      zinc: { amount: 3.5, unit: "mg" },
    },
  },
  {
    name: "美赞臣蓝臻 1段 (0-6个月)",
    brand: "MeadJohnson/美赞臣",
    stage: 1,
    scoopWeightG: 4.4,
    waterPerScoopMl: 30.0,
    reconstitutionRatio: 0.138,
    servingSizeUnit: "per_100g",
    isActive: true,
    notes: "富含乳铁蛋白与MFGM乳脂球膜",
    nutrients: {
      energy_kcal: { amount: 505, unit: "kcal" },
      protein: { amount: 10.4, unit: "g" },
      fat: { amount: 26.0, unit: "g" },
      carbohydrate: { amount: 56.5, unit: "g" },
      dha: { amount: 63, unit: "mg" },
      ara: { amount: 72, unit: "mg" },
      vitamin_a: { amount: 435, unit: "mcg RAE" },
      vitamin_d: { amount: 340, unit: "IU" },
      calcium: { amount: 355, unit: "mg" },
      iron: { amount: 5.3, unit: "mg" },
      zinc: { amount: 3.7, unit: "mg" },
    },
  },
  {
    name: "雀巢超启能恩 1段 (0-6个月/适度水解)",
    brand: "Nestle/雀巢",
    stage: 1,
    scoopWeightG: 4.35,
    waterPerScoopMl: 30.0,
    reconstitutionRatio: 0.135,
    servingSizeUnit: "per_100g",
    isActive: true,
    notes: "适度水解乳清蛋白，小分子好吸收抗过敏",
    nutrients: {
      energy_kcal: { amount: 495, unit: "kcal" },
      protein: { amount: 9.8, unit: "g" },
      fat: { amount: 25.0, unit: "g" },
      carbohydrate: { amount: 57.0, unit: "g" },
      dha: { amount: 58, unit: "mg" },
      ara: { amount: 58, unit: "mg" },
      vitamin_a: { amount: 410, unit: "mcg RAE" },
      vitamin_d: { amount: 360, unit: "IU" },
      calcium: { amount: 330, unit: "mg" },
      iron: { amount: 4.8, unit: "mg" },
      zinc: { amount: 3.4, unit: "mg" },
    },
  },
];

/**
 * 预置补剂产品库 (Presets)
 * 涵盖中国市场主流单方与复合营养补充剂
 */
export const PRESET_SUPPLEMENT_PRODUCTS: Omit<SupplementProduct, "id" | "familyId" | "createdAt" | "updatedAt">[] = [
  {
    name: "星鲨 维生素D3滴剂 (软胶囊型)",
    brand: "星鲨",
    dosageForm: "capsule",
    unitName: "粒",
    defaultDose: 1.0,
    isActive: true,
    notes: "每粒含维生素D3 400 IU (10微克)，经典国药准字",
    nutrients: {
      vitamin_d: { amount: 400, unit: "IU" },
    },
  },
  {
    name: "Ddrops 婴儿天然维生素D3滴剂",
    brand: "Ddrops",
    dosageForm: "drops",
    unitName: "滴",
    defaultDose: 1.0,
    isActive: true,
    notes: "每滴含维生素D3 400 IU，天然羊毛脂提取",
    nutrients: {
      vitamin_d: { amount: 400, unit: "IU" },
    },
  },
  {
    name: "伊可新 维生素AD滴剂 (绿葫芦 0-1岁)",
    brand: "达因/伊可新",
    dosageForm: "capsule",
    unitName: "粒",
    defaultDose: 1.0,
    isActive: true,
    notes: "0-1岁婴儿适用。每粒含维生素A 1500 IU (450 mcg RAE)，维生素D3 500 IU (12.5 mcg)",
    nutrients: {
      vitamin_a: { amount: 450, unit: "mcg RAE" },
      vitamin_d: { amount: 500, unit: "IU" },
    },
  },
  {
    name: "伊可新 维生素AD滴剂 (粉葫芦 1岁以上)",
    brand: "达因/伊可新",
    dosageForm: "capsule",
    unitName: "粒",
    defaultDose: 1.0,
    isActive: true,
    notes: "1岁以上幼儿适用。每粒含维生素A 2000 IU (600 mcg RAE)，维生素D3 700 IU (17.5 mcg)",
    nutrients: {
      vitamin_a: { amount: 600, unit: "mcg RAE" },
      vitamin_d: { amount: 700, unit: "IU" },
    },
  },
  {
    name: "Ostelin 婴幼儿液体乳钙 (含维生素D3+K2)",
    brand: "Ostelin/奥斯特林",
    dosageForm: "liquid_ml",
    unitName: "ml",
    defaultDose: 1.0,
    isActive: true,
    notes: "每1ml含钙 100mg，维生素D3 200 IU (5 mcg)，维生素K2 5 mcg。复合补钙补D",
    nutrients: {
      calcium: { amount: 100, unit: "mg" },
      vitamin_d: { amount: 200, unit: "IU" },
      vitamin_k: { amount: 5, unit: "mcg" },
    },
  },
  {
    name: "童年时光 (ChildLife) 婴幼儿液体钙镁锌滴剂",
    brand: "ChildLife",
    dosageForm: "liquid_ml",
    unitName: "ml",
    defaultDose: 5.0,
    isActive: true,
    notes: "每5ml含钙 84mg，镁 38mg，锌 0.67mg，维生素D3 33 IU",
    nutrients: {
      calcium: { amount: 84, unit: "mg" },
      magnesium: { amount: 38, unit: "mg" },
      zinc: { amount: 0.67, unit: "mg" },
      vitamin_d: { amount: 33, unit: "IU" },
    },
  },
  {
    name: "艾瑞可 (Eric Favre) 婴幼儿液体铁滴剂",
    brand: "Eric Favre/艾瑞可",
    dosageForm: "liquid_ml",
    unitName: "ml",
    defaultDose: 1.0,
    isActive: true,
    notes: "每1ml含铁 7mg，并复配维生素B群 (B1 0.55mg, B2 0.7mg, B6 0.7mg, B12 1.25mcg)",
    nutrients: {
      iron: { amount: 7.0, unit: "mg" },
      vitamin_b1: { amount: 0.55, unit: "mg" },
      vitamin_b2: { amount: 0.7, unit: "mg" },
      vitamin_b6: { amount: 0.7, unit: "mg" },
      vitamin_b12: { amount: 1.25, unit: "mcg" },
    },
  },
  {
    name: "艾瑞可 (Eric Favre) 婴幼儿液体锌滴剂",
    brand: "Eric Favre/艾瑞可",
    dosageForm: "liquid_ml",
    unitName: "ml",
    defaultDose: 1.0,
    isActive: true,
    notes: "每1ml含锌 3mg，维生素B6 0.7mg",
    nutrients: {
      zinc: { amount: 3.0, unit: "mg" },
      vitamin_b6: { amount: 0.7, unit: "mg" },
    },
  },
  {
    name: "纽曼思 (Nemans) 婴幼儿DHA藻油软胶囊",
    brand: "Nemans/纽曼思",
    dosageForm: "capsule",
    unitName: "粒",
    defaultDose: 1.0,
    isActive: true,
    notes: "每粒含高纯度裂壶藻DHA 100mg，无重金属污染",
    nutrients: {
      dha: { amount: 100, unit: "mg" },
    },
  },
  {
    name: "拜奥 (BioGaia) 罗伊氏乳杆菌益生菌滴剂 (含维D版)",
    brand: "BioGaia/拜奥",
    dosageForm: "drops",
    unitName: "滴",
    defaultDose: 5.0,
    isActive: true,
    notes: "每5滴含罗伊氏乳杆菌 1亿CFU + 维生素D3 400 IU",
    nutrients: {
      vitamin_d: { amount: 400, unit: "IU" },
    },
  },
];
