import type { FormulaProduct, SupplementProduct } from "@/types/nutrition";

/**
 * 预置配方奶粉产品库 (Presets)
 * 涵盖中国市场及海淘主流：爱他美德版、澳版、新加坡版、国行新国标版各段位，以及主流母婴奶粉
 * 包含精准单勺克重、加水量、冲调折算浓度与全量核心营养素
 */
export const PRESET_FORMULA_PRODUCTS: Omit<FormulaProduct, "id" | "familyId" | "createdAt" | "updatedAt">[] = [
  // ==================== 1. 爱他美 德版 (Germany Aptamil) ====================
  {
    name: "德国爱他美白金版 Profutura Pre段 (0-6个月)",
    brand: "Aptamil/爱他美(德版)",
    stage: 1,
    scoopWeightG: 4.6,
    waterPerScoopMl: 30.0,
    reconstitutionRatio: 0.138,
    servingSizeUnit: "per_100g",
    isActive: true,
    notes: "德国本土白金双重进阶DUOAdvance配方，全乳糖无淀粉，专为新生儿消化吸收设计",
    nutrients: {
      energy_kcal: { amount: 475, unit: "kcal" },
      energy_kj: { amount: 1988, unit: "kJ" },
      protein: { amount: 9.7, unit: "g" },
      fat: { amount: 24.7, unit: "g" },
      carbohydrate: { amount: 53.0, unit: "g" },
      dha: { amount: 120, unit: "mg" },
      ara: { amount: 120, unit: "mg" },
      vitamin_a: { amount: 420, unit: "mcg RAE" },
      vitamin_d: { amount: 400, unit: "IU" },
      calcium: { amount: 390, unit: "mg" },
      iron: { amount: 3.9, unit: "mg" },
      zinc: { amount: 3.5, unit: "mg" },
      vitamin_c: { amount: 67, unit: "mg" },
      vitamin_b1: { amount: 0.5, unit: "mg" },
      vitamin_b2: { amount: 0.8, unit: "mg" },
    },
  },
  {
    name: "德国爱他美白金版 Profutura 1段 (0-6个月)",
    brand: "Aptamil/爱他美(德版)",
    stage: 1,
    scoopWeightG: 4.6,
    waterPerScoopMl: 30.0,
    reconstitutionRatio: 0.138,
    servingSizeUnit: "per_100g",
    isActive: true,
    notes: "德国本土白金1段，添加天然乳脂与HMO母乳低聚糖，支持免疫与肠道健康",
    nutrients: {
      energy_kcal: { amount: 480, unit: "kcal" },
      energy_kj: { amount: 2008, unit: "kJ" },
      protein: { amount: 9.8, unit: "g" },
      fat: { amount: 24.8, unit: "g" },
      carbohydrate: { amount: 53.5, unit: "g" },
      dha: { amount: 120, unit: "mg" },
      ara: { amount: 120, unit: "mg" },
      vitamin_a: { amount: 430, unit: "mcg RAE" },
      vitamin_d: { amount: 400, unit: "IU" },
      calcium: { amount: 400, unit: "mg" },
      iron: { amount: 4.0, unit: "mg" },
      zinc: { amount: 3.6, unit: "mg" },
      vitamin_c: { amount: 68, unit: "mg" },
    },
  },
  {
    name: "德国爱他美白金版 Profutura 2段 (6-12个月)",
    brand: "Aptamil/爱他美(德版)",
    stage: 2,
    scoopWeightG: 4.7,
    waterPerScoopMl: 30.0,
    reconstitutionRatio: 0.141,
    servingSizeUnit: "per_100g",
    isActive: true,
    notes: "德国本土白金2段，针对较大婴儿强化铁、钙与双重益生元组合",
    nutrients: {
      energy_kcal: { amount: 485, unit: "kcal" },
      protein: { amount: 10.5, unit: "g" },
      fat: { amount: 23.5, unit: "g" },
      carbohydrate: { amount: 57.0, unit: "g" },
      dha: { amount: 120, unit: "mg" },
      ara: { amount: 120, unit: "mg" },
      vitamin_a: { amount: 450, unit: "mcg RAE" },
      vitamin_d: { amount: 400, unit: "IU" },
      calcium: { amount: 510, unit: "mg" },
      iron: { amount: 7.0, unit: "mg" },
      zinc: { amount: 3.8, unit: "mg" },
      vitamin_c: { amount: 62, unit: "mg" },
    },
  },
  {
    name: "德国爱他美白金版 Profutura 1+段/3段 (12-24个月)",
    brand: "Aptamil/爱他美(德版)",
    stage: 3,
    scoopWeightG: 4.8,
    waterPerScoopMl: 30.0,
    reconstitutionRatio: 0.144,
    servingSizeUnit: "per_100g",
    isActive: true,
    notes: "德国本土白金1+段，针对幼儿期骨骼与眼脑发育，富含维生素D、钙与碘",
    nutrients: {
      energy_kcal: { amount: 465, unit: "kcal" },
      protein: { amount: 11.5, unit: "g" },
      fat: { amount: 19.5, unit: "g" },
      carbohydrate: { amount: 60.5, unit: "g" },
      dha: { amount: 90, unit: "mg" },
      vitamin_a: { amount: 480, unit: "mcg RAE" },
      vitamin_d: { amount: 360, unit: "IU" },
      calcium: { amount: 650, unit: "mg" },
      iron: { amount: 7.5, unit: "mg" },
      zinc: { amount: 4.0, unit: "mg" },
    },
  },
  {
    name: "德国爱他美白金版 Profutura 2+段 (24个月以上)",
    brand: "Aptamil/爱他美(德版)",
    stage: 3,
    scoopWeightG: 4.8,
    waterPerScoopMl: 30.0,
    reconstitutionRatio: 0.144,
    servingSizeUnit: "per_100g",
    isActive: true,
    notes: "德国本土白金2+段，针对2岁以上学龄前儿童，强化钙铁锌与优质蛋白",
    nutrients: {
      energy_kcal: { amount: 455, unit: "kcal" },
      protein: { amount: 12.0, unit: "g" },
      fat: { amount: 18.0, unit: "g" },
      carbohydrate: { amount: 61.5, unit: "g" },
      dha: { amount: 80, unit: "mg" },
      vitamin_a: { amount: 500, unit: "mcg RAE" },
      vitamin_d: { amount: 340, unit: "IU" },
      calcium: { amount: 700, unit: "mg" },
      iron: { amount: 7.0, unit: "mg" },
      zinc: { amount: 4.0, unit: "mg" },
    },
  },
  {
    name: "德国爱他美经典蓝罐 Pronutra Pre段 (0-6个月)",
    brand: "Aptamil/爱他美(德版)",
    stage: 1,
    scoopWeightG: 4.5,
    waterPerScoopMl: 30.0,
    reconstitutionRatio: 0.136,
    servingSizeUnit: "per_100g",
    isActive: true,
    notes: "德国本土经典蓝罐Pre段，9:1益生元GOS/FOS组合，全乳糖温和易消化",
    nutrients: {
      energy_kcal: { amount: 472, unit: "kcal" },
      protein: { amount: 9.5, unit: "g" },
      fat: { amount: 24.5, unit: "g" },
      carbohydrate: { amount: 53.0, unit: "g" },
      dha: { amount: 110, unit: "mg" },
      ara: { amount: 110, unit: "mg" },
      vitamin_a: { amount: 410, unit: "mcg RAE" },
      vitamin_d: { amount: 390, unit: "IU" },
      calcium: { amount: 380, unit: "mg" },
      iron: { amount: 3.8, unit: "mg" },
      zinc: { amount: 3.4, unit: "mg" },
    },
  },
  {
    name: "德国爱他美经典蓝罐 Pronutra 1段 (0-6个月)",
    brand: "Aptamil/爱他美(德版)",
    stage: 1,
    scoopWeightG: 4.5,
    waterPerScoopMl: 30.0,
    reconstitutionRatio: 0.136,
    servingSizeUnit: "per_100g",
    isActive: true,
    notes: "德国本土经典蓝罐1段，含DHA与经典益生元配方",
    nutrients: {
      energy_kcal: { amount: 478, unit: "kcal" },
      protein: { amount: 9.6, unit: "g" },
      fat: { amount: 24.6, unit: "g" },
      carbohydrate: { amount: 53.5, unit: "g" },
      dha: { amount: 110, unit: "mg" },
      ara: { amount: 110, unit: "mg" },
      vitamin_a: { amount: 420, unit: "mcg RAE" },
      vitamin_d: { amount: 390, unit: "IU" },
      calcium: { amount: 390, unit: "mg" },
      iron: { amount: 3.9, unit: "mg" },
      zinc: { amount: 3.5, unit: "mg" },
    },
  },
  {
    name: "德国爱他美经典蓝罐 Pronutra 2段 (6-12个月)",
    brand: "Aptamil/爱他美(德版)",
    stage: 2,
    scoopWeightG: 4.6,
    waterPerScoopMl: 30.0,
    reconstitutionRatio: 0.139,
    servingSizeUnit: "per_100g",
    isActive: true,
    notes: "德国本土经典蓝罐2段，满足断奶期婴儿铁与微量元素需求",
    nutrients: {
      energy_kcal: { amount: 480, unit: "kcal" },
      protein: { amount: 10.3, unit: "g" },
      fat: { amount: 23.2, unit: "g" },
      carbohydrate: { amount: 57.0, unit: "g" },
      dha: { amount: 110, unit: "mg" },
      ara: { amount: 110, unit: "mg" },
      vitamin_a: { amount: 440, unit: "mcg RAE" },
      vitamin_d: { amount: 380, unit: "IU" },
      calcium: { amount: 500, unit: "mg" },
      iron: { amount: 6.8, unit: "mg" },
      zinc: { amount: 3.7, unit: "mg" },
    },
  },
  {
    name: "德国爱他美经典蓝罐 Pronutra 1+段 (12-24个月)",
    brand: "Aptamil/爱他美(德版)",
    stage: 3,
    scoopWeightG: 4.7,
    waterPerScoopMl: 30.0,
    reconstitutionRatio: 0.142,
    servingSizeUnit: "per_100g",
    isActive: true,
    notes: "德国本土经典蓝罐1+段，助力幼儿骨骼生长与活力",
    nutrients: {
      energy_kcal: { amount: 460, unit: "kcal" },
      protein: { amount: 11.2, unit: "g" },
      fat: { amount: 19.0, unit: "g" },
      carbohydrate: { amount: 60.0, unit: "g" },
      dha: { amount: 85, unit: "mg" },
      vitamin_a: { amount: 470, unit: "mcg RAE" },
      vitamin_d: { amount: 350, unit: "IU" },
      calcium: { amount: 620, unit: "mg" },
      iron: { amount: 7.2, unit: "mg" },
      zinc: { amount: 3.8, unit: "mg" },
    },
  },
  {
    name: "德国爱他美HA适度水解低敏 1段 (0-6个月)",
    brand: "Aptamil/爱他美(德版)",
    stage: 1,
    scoopWeightG: 4.6,
    waterPerScoopMl: 30.0,
    reconstitutionRatio: 0.138,
    servingSizeUnit: "per_100g",
    isActive: true,
    notes: "德国本土HA适度水解配方，小分子乳清蛋白，降低牛奶蛋白过敏风险",
    nutrients: {
      energy_kcal: { amount: 475, unit: "kcal" },
      protein: { amount: 9.7, unit: "g" },
      fat: { amount: 24.5, unit: "g" },
      carbohydrate: { amount: 53.5, unit: "g" },
      dha: { amount: 115, unit: "mg" },
      ara: { amount: 115, unit: "mg" },
      vitamin_a: { amount: 420, unit: "mcg RAE" },
      vitamin_d: { amount: 390, unit: "IU" },
      calcium: { amount: 390, unit: "mg" },
      iron: { amount: 3.9, unit: "mg" },
      zinc: { amount: 3.5, unit: "mg" },
    },
  },

  // ==================== 2. 爱他美 澳版 (Australia & NZ Aptamil) ====================
  {
    name: "澳洲爱他美白金版 Profutura 1段 (0-6个月)",
    brand: "Aptamil/爱他美(澳版)",
    stage: 1,
    scoopWeightG: 7.3,
    waterPerScoopMl: 50.0,
    reconstitutionRatio: 0.146,
    servingSizeUnit: "per_100g",
    isActive: true,
    notes: "澳洲本土白金1段，50ml水配1勺(7.3g)，添加短双歧杆菌M-16V活性益生菌与高含量DHA",
    nutrients: {
      energy_kcal: { amount: 490, unit: "kcal" },
      protein: { amount: 9.8, unit: "g" },
      fat: { amount: 25.5, unit: "g" },
      carbohydrate: { amount: 54.5, unit: "g" },
      dha: { amount: 110, unit: "mg" },
      ara: { amount: 110, unit: "mg" },
      vitamin_a: { amount: 430, unit: "mcg RAE" },
      vitamin_d: { amount: 380, unit: "IU" },
      calcium: { amount: 380, unit: "mg" },
      iron: { amount: 5.2, unit: "mg" },
      zinc: { amount: 3.8, unit: "mg" },
      vitamin_c: { amount: 65, unit: "mg" },
      nucleotides: { amount: 20, unit: "mg" },
    },
  },
  {
    name: "澳洲爱他美白金版 Profutura 2段 (6-12个月)",
    brand: "Aptamil/爱他美(澳版)",
    stage: 2,
    scoopWeightG: 7.3,
    waterPerScoopMl: 50.0,
    reconstitutionRatio: 0.146,
    servingSizeUnit: "per_100g",
    isActive: true,
    notes: "澳洲本土白金2段，50ml水配1勺(7.3g)，强化铁吸收与益生菌益生元双重守护",
    nutrients: {
      energy_kcal: { amount: 480, unit: "kcal" },
      protein: { amount: 11.2, unit: "g" },
      fat: { amount: 23.0, unit: "g" },
      carbohydrate: { amount: 56.5, unit: "g" },
      dha: { amount: 100, unit: "mg" },
      ara: { amount: 100, unit: "mg" },
      vitamin_a: { amount: 450, unit: "mcg RAE" },
      vitamin_d: { amount: 370, unit: "IU" },
      calcium: { amount: 530, unit: "mg" },
      iron: { amount: 7.5, unit: "mg" },
      zinc: { amount: 4.2, unit: "mg" },
    },
  },
  {
    name: "澳洲爱他美白金版 Profutura 3段 (1-2岁)",
    brand: "Aptamil/爱他美(澳版)",
    stage: 3,
    scoopWeightG: 7.3,
    waterPerScoopMl: 50.0,
    reconstitutionRatio: 0.146,
    servingSizeUnit: "per_100g",
    isActive: true,
    notes: "澳洲本土白金3段，50ml水配1勺(7.3g)，助力眼脑发育与抵抗力构建",
    nutrients: {
      energy_kcal: { amount: 460, unit: "kcal" },
      protein: { amount: 13.0, unit: "g" },
      fat: { amount: 19.5, unit: "g" },
      carbohydrate: { amount: 58.0, unit: "g" },
      dha: { amount: 90, unit: "mg" },
      vitamin_a: { amount: 480, unit: "mcg RAE" },
      vitamin_d: { amount: 330, unit: "IU" },
      calcium: { amount: 680, unit: "mg" },
      iron: { amount: 7.8, unit: "mg" },
      zinc: { amount: 4.0, unit: "mg" },
    },
  },
  {
    name: "澳洲爱他美白金版 Profutura 4段 (2岁以上)",
    brand: "Aptamil/爱他美(澳版)",
    stage: 3,
    scoopWeightG: 7.3,
    waterPerScoopMl: 50.0,
    reconstitutionRatio: 0.146,
    servingSizeUnit: "per_100g",
    isActive: true,
    notes: "澳洲本土白金4段，50ml水配1勺(7.3g)，提供学龄前儿童成长必需营养",
    nutrients: {
      energy_kcal: { amount: 450, unit: "kcal" },
      protein: { amount: 13.5, unit: "g" },
      fat: { amount: 18.0, unit: "g" },
      carbohydrate: { amount: 59.5, unit: "g" },
      dha: { amount: 80, unit: "mg" },
      vitamin_a: { amount: 500, unit: "mcg RAE" },
      vitamin_d: { amount: 320, unit: "IU" },
      calcium: { amount: 720, unit: "mg" },
      iron: { amount: 7.0, unit: "mg" },
      zinc: { amount: 4.0, unit: "mg" },
    },
  },
  {
    name: "澳洲爱他美金装 Gold+ 1段 (0-6个月)",
    brand: "Aptamil/爱他美(澳版)",
    stage: 1,
    scoopWeightG: 7.3,
    waterPerScoopMl: 50.0,
    reconstitutionRatio: 0.146,
    servingSizeUnit: "per_100g",
    isActive: true,
    notes: "澳洲经典金装1段，50ml水配1勺(7.3g)，经典益生元GOS/FOS配方",
    nutrients: {
      energy_kcal: { amount: 485, unit: "kcal" },
      protein: { amount: 9.7, unit: "g" },
      fat: { amount: 25.0, unit: "g" },
      carbohydrate: { amount: 54.0, unit: "g" },
      dha: { amount: 95, unit: "mg" },
      ara: { amount: 95, unit: "mg" },
      vitamin_a: { amount: 420, unit: "mcg RAE" },
      vitamin_d: { amount: 370, unit: "IU" },
      calcium: { amount: 370, unit: "mg" },
      iron: { amount: 5.0, unit: "mg" },
      zinc: { amount: 3.6, unit: "mg" },
    },
  },
  {
    name: "澳洲爱他美金装 Gold+ 2段 (6-12个月)",
    brand: "Aptamil/爱他美(澳版)",
    stage: 2,
    scoopWeightG: 7.3,
    waterPerScoopMl: 50.0,
    reconstitutionRatio: 0.146,
    servingSizeUnit: "per_100g",
    isActive: true,
    notes: "澳洲经典金装2段，50ml水配1勺(7.3g)",
    nutrients: {
      energy_kcal: { amount: 475, unit: "kcal" },
      protein: { amount: 11.0, unit: "g" },
      fat: { amount: 22.5, unit: "g" },
      carbohydrate: { amount: 56.0, unit: "g" },
      dha: { amount: 90, unit: "mg" },
      ara: { amount: 90, unit: "mg" },
      vitamin_a: { amount: 440, unit: "mcg RAE" },
      vitamin_d: { amount: 360, unit: "IU" },
      calcium: { amount: 510, unit: "mg" },
      iron: { amount: 7.2, unit: "mg" },
      zinc: { amount: 4.0, unit: "mg" },
    },
  },
  {
    name: "澳洲爱他美奇迹绿罐有机A2 1段 (0-6个月)",
    brand: "Aptamil/爱他美(澳版)",
    stage: 1,
    scoopWeightG: 7.3,
    waterPerScoopMl: 50.0,
    reconstitutionRatio: 0.146,
    servingSizeUnit: "per_100g",
    isActive: true,
    notes: "澳洲爱他美奇迹绿罐Essensis系列，有机A2蛋白奶源，双重有机HMO+短双歧杆菌M-16V",
    nutrients: {
      energy_kcal: { amount: 495, unit: "kcal" },
      protein: { amount: 9.9, unit: "g" },
      fat: { amount: 26.0, unit: "g" },
      carbohydrate: { amount: 54.0, unit: "g" },
      dha: { amount: 115, unit: "mg" },
      ara: { amount: 115, unit: "mg" },
      vitamin_a: { amount: 440, unit: "mcg RAE" },
      vitamin_d: { amount: 390, unit: "IU" },
      calcium: { amount: 390, unit: "mg" },
      iron: { amount: 5.3, unit: "mg" },
      zinc: { amount: 3.9, unit: "mg" },
    },
  },
  {
    name: "澳洲爱他美白金纯羊奶粉 1段 (0-6个月)",
    brand: "Aptamil/爱他美(澳版)",
    stage: 1,
    scoopWeightG: 7.3,
    waterPerScoopMl: 50.0,
    reconstitutionRatio: 0.146,
    servingSizeUnit: "per_100g",
    isActive: true,
    notes: "澳洲爱他美Essensis白金纯羊奶1段，纯羊乳小分子好消化，亲和低敏，50ml水配1勺(7.3g)",
    nutrients: {
      energy_kcal: { amount: 492, unit: "kcal" },
      protein: { amount: 9.8, unit: "g" },
      fat: { amount: 25.8, unit: "g" },
      carbohydrate: { amount: 54.2, unit: "g" },
      dha: { amount: 110, unit: "mg" },
      ara: { amount: 110, unit: "mg" },
      vitamin_a: { amount: 430, unit: "mcg RAE" },
      vitamin_d: { amount: 380, unit: "IU" },
      calcium: { amount: 385, unit: "mg" },
      iron: { amount: 5.2, unit: "mg" },
      zinc: { amount: 3.8, unit: "mg" },
    },
  },

  // ==================== 3. 爱他美 新加坡版/东南亚亚太版 (Singapore Aptamil) ====================
  {
    name: "新加坡版爱他美金装 Gold+ 1段 (0-6个月)",
    brand: "Aptamil/爱他美(新加坡版)",
    stage: 1,
    scoopWeightG: 4.5,
    waterPerScoopMl: 30.0,
    reconstitutionRatio: 0.136,
    servingSizeUnit: "per_100g",
    isActive: true,
    notes: "新加坡原装Aptamil Gold+ 1段，Pronutra+专利益生元配方，30ml水配1勺(4.5g)",
    nutrients: {
      energy_kcal: { amount: 488, unit: "kcal" },
      protein: { amount: 9.8, unit: "g" },
      fat: { amount: 24.6, unit: "g" },
      carbohydrate: { amount: 55.0, unit: "g" },
      dha: { amount: 70, unit: "mg" },
      ara: { amount: 70, unit: "mg" },
      vitamin_a: { amount: 420, unit: "mcg RAE" },
      vitamin_d: { amount: 370, unit: "IU" },
      calcium: { amount: 360, unit: "mg" },
      iron: { amount: 4.8, unit: "mg" },
      zinc: { amount: 3.6, unit: "mg" },
      vitamin_c: { amount: 60, unit: "mg" },
    },
  },
  {
    name: "新加坡版爱他美金装 Gold+ 2段 (6-12个月)",
    brand: "Aptamil/爱他美(新加坡版)",
    stage: 2,
    scoopWeightG: 4.6,
    waterPerScoopMl: 30.0,
    reconstitutionRatio: 0.139,
    servingSizeUnit: "per_100g",
    isActive: true,
    notes: "新加坡原装Aptamil Gold+ 2段，30ml水配1勺(4.6g)",
    nutrients: {
      energy_kcal: { amount: 478, unit: "kcal" },
      protein: { amount: 11.5, unit: "g" },
      fat: { amount: 22.0, unit: "g" },
      carbohydrate: { amount: 57.0, unit: "g" },
      dha: { amount: 68, unit: "mg" },
      ara: { amount: 68, unit: "mg" },
      vitamin_a: { amount: 440, unit: "mcg RAE" },
      vitamin_d: { amount: 360, unit: "IU" },
      calcium: { amount: 500, unit: "mg" },
      iron: { amount: 6.8, unit: "mg" },
      zinc: { amount: 3.9, unit: "mg" },
    },
  },
  {
    name: "新加坡版爱他美金装 Gold+ 3段 (1-3岁)",
    brand: "Aptamil/爱他美(新加坡版)",
    stage: 3,
    scoopWeightG: 4.7,
    waterPerScoopMl: 30.0,
    reconstitutionRatio: 0.142,
    servingSizeUnit: "per_100g",
    isActive: true,
    notes: "新加坡原装Aptamil Gold+ 3段，30ml水配1勺(4.7g)",
    nutrients: {
      energy_kcal: { amount: 460, unit: "kcal" },
      protein: { amount: 13.5, unit: "g" },
      fat: { amount: 19.0, unit: "g" },
      carbohydrate: { amount: 59.0, unit: "g" },
      dha: { amount: 60, unit: "mg" },
      vitamin_a: { amount: 470, unit: "mcg RAE" },
      vitamin_d: { amount: 330, unit: "IU" },
      calcium: { amount: 630, unit: "mg" },
      iron: { amount: 7.0, unit: "mg" },
      zinc: { amount: 3.8, unit: "mg" },
    },
  },
  {
    name: "新加坡版爱他美白金版 Profutura 1段 (0-6个月)",
    brand: "Aptamil/爱他美(新加坡版)",
    stage: 1,
    scoopWeightG: 4.6,
    waterPerScoopMl: 30.0,
    reconstitutionRatio: 0.138,
    servingSizeUnit: "per_100g",
    isActive: true,
    notes: "新加坡版爱他美白金1段，含高含量DHA与双重益生元，30ml水配1勺(4.6g)",
    nutrients: {
      energy_kcal: { amount: 485, unit: "kcal" },
      protein: { amount: 9.8, unit: "g" },
      fat: { amount: 24.8, unit: "g" },
      carbohydrate: { amount: 54.0, unit: "g" },
      dha: { amount: 110, unit: "mg" },
      ara: { amount: 110, unit: "mg" },
      vitamin_a: { amount: 430, unit: "mcg RAE" },
      vitamin_d: { amount: 380, unit: "IU" },
      calcium: { amount: 380, unit: "mg" },
      iron: { amount: 4.9, unit: "mg" },
      zinc: { amount: 3.7, unit: "mg" },
    },
  },

  // ==================== 4. 爱他美 国内版/国行新国标 (China Domestic Aptamil) ====================
  {
    name: "爱他美卓萃 1段 (0-6个月/国行新国标)",
    brand: "Aptamil/爱他美(国内版)",
    stage: 1,
    scoopWeightG: 4.3,
    waterPerScoopMl: 30.0,
    reconstitutionRatio: 0.135,
    servingSizeUnit: "per_100g",
    isActive: true,
    notes: "欧洲原装进口，新国标卓萃，添加天然乳脂、全乳糖与NuMMOs益生元组合",
    nutrients: {
      energy_kcal: { amount: 485, unit: "kcal" },
      energy_kj: { amount: 2030, unit: "kJ" },
      protein: { amount: 9.8, unit: "g" },
      fat: { amount: 24.5, unit: "g" },
      carbohydrate: { amount: 55.2, unit: "g" },
      linoleic_acid: { amount: 3400, unit: "mg" },
      alpha_linolenic_acid: { amount: 380, unit: "mg" },
      dha: { amount: 65, unit: "mg" },
      ara: { amount: 65, unit: "mg" },
      vitamin_a: { amount: 420, unit: "mcg RAE" },
      vitamin_d: { amount: 380, unit: "IU" },
      vitamin_e: { amount: 8.5, unit: "mg α-TE" },
      vitamin_k: { amount: 38, unit: "mcg" },
      vitamin_b1: { amount: 0.45, unit: "mg" },
      vitamin_b2: { amount: 0.75, unit: "mg" },
      vitamin_b6: { amount: 0.38, unit: "mg" },
      vitamin_b12: { amount: 1.5, unit: "mcg" },
      vitamin_c: { amount: 65, unit: "mg" },
      folate: { amount: 85, unit: "mcg DFE" },
      niacin: { amount: 3.5, unit: "mg NE" },
      pantothenic_acid: { amount: 2.8, unit: "mg" },
      biotin: { amount: 12, unit: "mcg" },
      choline: { amount: 120, unit: "mg" },
      calcium: { amount: 340, unit: "mg" },
      phosphorus: { amount: 210, unit: "mg" },
      potassium: { amount: 500, unit: "mg" },
      sodium: { amount: 160, unit: "mg" },
      magnesium: { amount: 38, unit: "mg" },
      iron: { amount: 5.2, unit: "mg" },
      zinc: { amount: 3.8, unit: "mg" },
      copper: { amount: 310, unit: "mcg" },
      iodine: { amount: 75, unit: "mcg" },
      selenium: { amount: 14, unit: "mcg" },
      taurine: { amount: 35, unit: "mg" },
      nucleotides: { amount: 22, unit: "mg" },
    },
  },
  {
    name: "爱他美卓萃 2段 (6-12个月/国行新国标)",
    brand: "Aptamil/爱他美(国内版)",
    stage: 2,
    scoopWeightG: 4.5,
    waterPerScoopMl: 30.0,
    reconstitutionRatio: 0.14,
    servingSizeUnit: "per_100g",
    isActive: true,
    notes: "国行新国标卓萃2段，适合较大婴儿，强化铁、锌与钙质吸收",
    nutrients: {
      energy_kcal: { amount: 472, unit: "kcal" },
      energy_kj: { amount: 1975, unit: "kJ" },
      protein: { amount: 12.5, unit: "g" },
      fat: { amount: 21.0, unit: "g" },
      carbohydrate: { amount: 57.5, unit: "g" },
      dha: { amount: 60, unit: "mg" },
      ara: { amount: 60, unit: "mg" },
      vitamin_a: { amount: 450, unit: "mcg RAE" },
      vitamin_d: { amount: 360, unit: "IU" },
      calcium: { amount: 520, unit: "mg" },
      phosphorus: { amount: 310, unit: "mg" },
      iron: { amount: 7.2, unit: "mg" },
      zinc: { amount: 4.2, unit: "mg" },
      vitamin_c: { amount: 60, unit: "mg" },
      vitamin_b1: { amount: 0.5, unit: "mg" },
      vitamin_b2: { amount: 0.8, unit: "mg" },
    },
  },
  {
    name: "爱他美卓萃 3段 (12-36个月/国行新国标)",
    brand: "Aptamil/爱他美(国内版)",
    stage: 3,
    scoopWeightG: 4.8,
    waterPerScoopMl: 30.0,
    reconstitutionRatio: 0.145,
    servingSizeUnit: "per_100g",
    isActive: true,
    notes: "国行新国标卓萃3段，适合幼儿期，富含钙质、膳食纤维与优量DHA",
    nutrients: {
      energy_kcal: { amount: 460, unit: "kcal" },
      protein: { amount: 14.5, unit: "g" },
      fat: { amount: 19.5, unit: "g" },
      carbohydrate: { amount: 60.0, unit: "g" },
      dha: { amount: 55, unit: "mg" },
      vitamin_a: { amount: 480, unit: "mcg RAE" },
      vitamin_d: { amount: 320, unit: "IU" },
      calcium: { amount: 650, unit: "mg" },
      iron: { amount: 6.8, unit: "mg" },
      zinc: { amount: 3.9, unit: "mg" },
    },
  },
  {
    name: "爱他美卓傲 1段 (0-6个月/国行新国标)",
    brand: "Aptamil/爱他美(国内版)",
    stage: 1,
    scoopWeightG: 4.3,
    waterPerScoopMl: 30.0,
    reconstitutionRatio: 0.135,
    servingSizeUnit: "per_100g",
    isActive: true,
    notes: "国行新国标卓傲1段，9:1优量益生元与全乳糖配方，清淡不上火",
    nutrients: {
      energy_kcal: { amount: 490, unit: "kcal" },
      protein: { amount: 9.8, unit: "g" },
      fat: { amount: 25.0, unit: "g" },
      carbohydrate: { amount: 55.5, unit: "g" },
      dha: { amount: 62, unit: "mg" },
      ara: { amount: 62, unit: "mg" },
      vitamin_a: { amount: 420, unit: "mcg RAE" },
      vitamin_d: { amount: 370, unit: "IU" },
      calcium: { amount: 350, unit: "mg" },
      iron: { amount: 5.1, unit: "mg" },
      zinc: { amount: 3.7, unit: "mg" },
    },
  },
  {
    name: "爱他美卓傲 2段 (6-12个月/国行新国标)",
    brand: "Aptamil/爱他美(国内版)",
    stage: 2,
    scoopWeightG: 4.5,
    waterPerScoopMl: 30.0,
    reconstitutionRatio: 0.14,
    servingSizeUnit: "per_100g",
    isActive: true,
    notes: "国行新国标卓傲2段，强化铁锌与益生元组合",
    nutrients: {
      energy_kcal: { amount: 475, unit: "kcal" },
      protein: { amount: 12.0, unit: "g" },
      fat: { amount: 21.5, unit: "g" },
      carbohydrate: { amount: 57.0, unit: "g" },
      dha: { amount: 58, unit: "mg" },
      ara: { amount: 58, unit: "mg" },
      vitamin_a: { amount: 450, unit: "mcg RAE" },
      vitamin_d: { amount: 360, unit: "IU" },
      calcium: { amount: 510, unit: "mg" },
      iron: { amount: 7.0, unit: "mg" },
      zinc: { amount: 4.0, unit: "mg" },
    },
  },
  {
    name: "爱他美卓傲 3段 (12-36个月/国行新国标)",
    brand: "Aptamil/爱他美(国内版)",
    stage: 3,
    scoopWeightG: 4.8,
    waterPerScoopMl: 30.0,
    reconstitutionRatio: 0.145,
    servingSizeUnit: "per_100g",
    isActive: true,
    notes: "国行新国标卓傲3段",
    nutrients: {
      energy_kcal: { amount: 465, unit: "kcal" },
      protein: { amount: 14.0, unit: "g" },
      fat: { amount: 20.0, unit: "g" },
      carbohydrate: { amount: 59.5, unit: "g" },
      dha: { amount: 52, unit: "mg" },
      vitamin_a: { amount: 470, unit: "mcg RAE" },
      vitamin_d: { amount: 330, unit: "IU" },
      calcium: { amount: 640, unit: "mg" },
      iron: { amount: 6.6, unit: "mg" },
      zinc: { amount: 3.8, unit: "mg" },
    },
  },
  {
    name: "爱他美经典版蓝罐 1段 (0-6个月/国行新国标)",
    brand: "Aptamil/爱他美(国内版)",
    stage: 1,
    scoopWeightG: 4.3,
    waterPerScoopMl: 30.0,
    reconstitutionRatio: 0.135,
    servingSizeUnit: "per_100g",
    isActive: true,
    notes: "国行新国标经典蓝罐1段，经典益生元GOS/FOS组合",
    nutrients: {
      energy_kcal: { amount: 485, unit: "kcal" },
      protein: { amount: 9.7, unit: "g" },
      fat: { amount: 24.5, unit: "g" },
      carbohydrate: { amount: 55.0, unit: "g" },
      dha: { amount: 60, unit: "mg" },
      ara: { amount: 60, unit: "mg" },
      vitamin_a: { amount: 420, unit: "mcg RAE" },
      vitamin_d: { amount: 370, unit: "IU" },
      calcium: { amount: 340, unit: "mg" },
      iron: { amount: 5.0, unit: "mg" },
      zinc: { amount: 3.6, unit: "mg" },
    },
  },
  {
    name: "爱他美领熠 1段 (0-6个月/国行新国标高端乳黄金球)",
    brand: "Aptamil/爱他美(国内版)",
    stage: 1,
    scoopWeightG: 4.4,
    waterPerScoopMl: 30.0,
    reconstitutionRatio: 0.137,
    servingSizeUnit: "per_100g",
    isActive: true,
    notes: "国行新国标高端领熠1段，含乳黄金球与适度水解低敏分子",
    nutrients: {
      energy_kcal: { amount: 492, unit: "kcal" },
      protein: { amount: 9.8, unit: "g" },
      fat: { amount: 25.5, unit: "g" },
      carbohydrate: { amount: 54.8, unit: "g" },
      dha: { amount: 66, unit: "mg" },
      ara: { amount: 66, unit: "mg" },
      vitamin_a: { amount: 430, unit: "mcg RAE" },
      vitamin_d: { amount: 380, unit: "IU" },
      calcium: { amount: 360, unit: "mg" },
      iron: { amount: 5.2, unit: "mg" },
      zinc: { amount: 3.8, unit: "mg" },
    },
  },
  {
    name: "爱他美悠蓝有机 1段 (0-6个月/国行新国标)",
    brand: "Aptamil/爱他美(国内版)",
    stage: 1,
    scoopWeightG: 4.4,
    waterPerScoopMl: 30.0,
    reconstitutionRatio: 0.137,
    servingSizeUnit: "per_100g",
    isActive: true,
    notes: "国行新国标悠蓝有机1段，有机A2蛋白奶源与有机全乳糖",
    nutrients: {
      energy_kcal: { amount: 488, unit: "kcal" },
      protein: { amount: 9.8, unit: "g" },
      fat: { amount: 25.0, unit: "g" },
      carbohydrate: { amount: 55.0, unit: "g" },
      dha: { amount: 64, unit: "mg" },
      ara: { amount: 64, unit: "mg" },
      vitamin_a: { amount: 425, unit: "mcg RAE" },
      vitamin_d: { amount: 375, unit: "IU" },
      calcium: { amount: 355, unit: "mg" },
      iron: { amount: 5.1, unit: "mg" },
      zinc: { amount: 3.7, unit: "mg" },
    },
  },

  // ==================== 5. 国内市场其他主流热门配方奶 ====================
  {
    name: "飞鹤星飞帆 1段 (0-6个月)",
    brand: "飞鹤/Feihe",
    stage: 1,
    scoopWeightG: 4.3,
    waterPerScoopMl: 30.0,
    reconstitutionRatio: 0.135,
    servingSizeUnit: "per_100g",
    isActive: true,
    notes: "中国宝宝体质专属配方，添加OPO结构脂与叶黄素",
    nutrients: {
      energy_kcal: { amount: 510, unit: "kcal" },
      protein: { amount: 10.5, unit: "g" },
      fat: { amount: 26.5, unit: "g" },
      carbohydrate: { amount: 56.0, unit: "g" },
      dha: { amount: 62, unit: "mg" },
      ara: { amount: 75, unit: "mg" },
      vitamin_a: { amount: 440, unit: "mcg RAE" },
      vitamin_d: { amount: 360, unit: "IU" },
      calcium: { amount: 360, unit: "mg" },
      iron: { amount: 5.5, unit: "mg" },
      zinc: { amount: 3.6, unit: "mg" },
      lutein: { amount: 120, unit: "mcg" },
    },
  },
  {
    name: "惠氏启赋蓝钻 1段 (0-6个月)",
    brand: "Wyeth/启赋",
    stage: 1,
    scoopWeightG: 4.3,
    waterPerScoopMl: 30.0,
    reconstitutionRatio: 0.135,
    servingSizeUnit: "per_100g",
    isActive: true,
    notes: "富含GSMO与乳源活性因子",
    nutrients: {
      energy_kcal: { amount: 512, unit: "kcal" },
      protein: { amount: 10.2, unit: "g" },
      fat: { amount: 26.8, unit: "g" },
      carbohydrate: { amount: 57.0, unit: "g" },
      dha: { amount: 65, unit: "mg" },
      ara: { amount: 65, unit: "mg" },
      vitamin_a: { amount: 430, unit: "mcg RAE" },
      vitamin_d: { amount: 350, unit: "IU" },
      calcium: { amount: 350, unit: "mg" },
      iron: { amount: 5.0, unit: "mg" },
      zinc: { amount: 3.5, unit: "mg" },
    },
  },
  {
    name: "美赞臣蓝臻 1段 (0-6个月)",
    brand: "MeadJohnson/美赞臣",
    stage: 1,
    scoopWeightG: 4.4,
    waterPerScoopMl: 30.0,
    reconstitutionRatio: 0.138,
    servingSizeUnit: "per_100g",
    isActive: true,
    notes: "富含乳铁蛋白与MFGM乳脂球膜",
    nutrients: {
      energy_kcal: { amount: 505, unit: "kcal" },
      protein: { amount: 10.4, unit: "g" },
      fat: { amount: 26.0, unit: "g" },
      carbohydrate: { amount: 56.5, unit: "g" },
      dha: { amount: 63, unit: "mg" },
      ara: { amount: 72, unit: "mg" },
      vitamin_a: { amount: 435, unit: "mcg RAE" },
      vitamin_d: { amount: 340, unit: "IU" },
      calcium: { amount: 355, unit: "mg" },
      iron: { amount: 5.3, unit: "mg" },
      zinc: { amount: 3.7, unit: "mg" },
    },
  },
  {
    name: "雀巢超启能恩 1段 (0-6个月/适度水解)",
    brand: "Nestle/雀巢",
    stage: 1,
    scoopWeightG: 4.35,
    waterPerScoopMl: 30.0,
    reconstitutionRatio: 0.135,
    servingSizeUnit: "per_100g",
    isActive: true,
    notes: "适度水解乳清蛋白，小分子好吸收抗过敏",
    nutrients: {
      energy_kcal: { amount: 495, unit: "kcal" },
      protein: { amount: 9.8, unit: "g" },
      fat: { amount: 25.0, unit: "g" },
      carbohydrate: { amount: 57.0, unit: "g" },
      dha: { amount: 58, unit: "mg" },
      ara: { amount: 58, unit: "mg" },
      vitamin_a: { amount: 410, unit: "mcg RAE" },
      vitamin_d: { amount: 360, unit: "IU" },
      calcium: { amount: 330, unit: "mg" },
      iron: { amount: 4.8, unit: "mg" },
      zinc: { amount: 3.4, unit: "mg" },
    },
  },
  {
    name: "皇家美素佳儿 1段 (0-6个月)",
    brand: "美素佳儿/Friso",
    stage: 1,
    scoopWeightG: 4.3,
    waterPerScoopMl: 30.0,
    reconstitutionRatio: 0.135,
    servingSizeUnit: "per_100g",
    isActive: true,
    notes: "荷兰第一层奶源精华，高达近40倍天然乳磷脂与天然OPO类似结构脂",
    nutrients: {
      energy_kcal: { amount: 508, unit: "kcal" },
      protein: { amount: 10.3, unit: "g" },
      fat: { amount: 26.5, unit: "g" },
      carbohydrate: { amount: 56.5, unit: "g" },
      dha: { amount: 60, unit: "mg" },
      ara: { amount: 60, unit: "mg" },
      vitamin_a: { amount: 430, unit: "mcg RAE" },
      vitamin_d: { amount: 350, unit: "IU" },
      calcium: { amount: 360, unit: "mg" },
      iron: { amount: 5.2, unit: "mg" },
      zinc: { amount: 3.5, unit: "mg" },
    },
  },
  {
    name: "皇家美素佳儿 2段 (6-12个月)",
    brand: "美素佳儿/Friso",
    stage: 2,
    scoopWeightG: 4.5,
    waterPerScoopMl: 30.0,
    reconstitutionRatio: 0.140,
    servingSizeUnit: "per_100g",
    isActive: true,
    notes: "荷兰第一层奶源精华，强化铁钙锌，助力转奶过渡",
    nutrients: {
      energy_kcal: { amount: 495, unit: "kcal" },
      protein: { amount: 12.0, unit: "g" },
      fat: { amount: 23.5, unit: "g" },
      carbohydrate: { amount: 58.0, unit: "g" },
      dha: { amount: 65, unit: "mg" },
      ara: { amount: 65, unit: "mg" },
      vitamin_a: { amount: 440, unit: "mcg RAE" },
      vitamin_d: { amount: 360, unit: "IU" },
      calcium: { amount: 480, unit: "mg" },
      iron: { amount: 6.8, unit: "mg" },
      zinc: { amount: 3.8, unit: "mg" },
    },
  },
  {
    name: "皇家美素佳儿 3段 (12-36个月)",
    brand: "美素佳儿/Friso",
    stage: 3,
    scoopWeightG: 4.7,
    waterPerScoopMl: 30.0,
    reconstitutionRatio: 0.145,
    servingSizeUnit: "per_100g",
    isActive: true,
    notes: "荷兰第一层奶源精华，添加天然乳脂与益生元组合，促进肠道保护力",
    nutrients: {
      energy_kcal: { amount: 470, unit: "kcal" },
      protein: { amount: 13.5, unit: "g" },
      fat: { amount: 20.0, unit: "g" },
      carbohydrate: { amount: 61.0, unit: "g" },
      dha: { amount: 50, unit: "mg" },
      ara: { amount: 50, unit: "mg" },
      vitamin_a: { amount: 450, unit: "mcg RAE" },
      vitamin_d: { amount: 380, unit: "IU" },
      calcium: { amount: 560, unit: "mg" },
      iron: { amount: 6.5, unit: "mg" },
      zinc: { amount: 4.0, unit: "mg" },
    },
  },
  {
    name: "雀巢小百肽 特殊医学用途全营养配方粉 (1-10岁)",
    brand: "Nestle/雀巢",
    stage: 3,
    scoopWeightG: 7.8,
    waterPerScoopMl: 35.0,
    reconstitutionRatio: 0.195,
    servingSizeUnit: "per_100g",
    isActive: true,
    notes: "特殊医学用途全营养配方粉（1-10岁）。100%小分子水解乳清蛋白+中链甘油三酯MCT，极易消化吸收，专为胃肠吸收不良、营养追赶设计",
    nutrients: {
      energy_kcal: { amount: 468, unit: "kcal" },
      protein: { amount: 13.7, unit: "g" },
      fat: { amount: 18.0, unit: "g" },
      carbohydrate: { amount: 62.8, unit: "g" },
      vitamin_a: { amount: 410, unit: "mcg RAE" },
      vitamin_d: { amount: 330, unit: "IU" },
      calcium: { amount: 460, unit: "mg" },
      iron: { amount: 5.6, unit: "mg" },
      zinc: { amount: 4.2, unit: "mg" },
    },
  },

  // ==================== 6. 纽迪希亚 纽荃星 / 特殊医学用途配方奶粉 (Nutricia Infatrini & FSMP) ====================
  {
    name: "纽迪希亚 纽荃星 婴儿高能量特医配方粉 (0-12个月)",
    brand: "纽迪希亚/Nutricia",
    stage: 1,
    scoopWeightG: 5.0,
    waterPerScoopMl: 22.5,
    reconstitutionRatio: 0.200,
    servingSizeUnit: "per_100g",
    isActive: true,
    notes: "特殊医学用途婴儿高能量配方粉（0-12月龄）。标准冲调4平勺(20g)兑90ml水，100ml奶液提供100kcal（普通奶粉1.5倍），蛋白能量比10.4%符合WHO追赶生长黄金标准，含MCT与GOS/FOS益生元，专为早产、低出生体重及体重生长落后婴儿设计",
    nutrients: {
      energy_kcal: { amount: 500, unit: "kcal" },
      energy_kj: { amount: 2090, unit: "kJ" },
      protein: { amount: 13.0, unit: "g" },
      fat: { amount: 26.5, unit: "g" },
      carbohydrate: { amount: 52.0, unit: "g" },
      linoleic_acid: { amount: 3900, unit: "mg" },
      alpha_linolenic_acid: { amount: 430, unit: "mg" },
      dha: { amount: 70, unit: "mg" },
      ara: { amount: 70, unit: "mg" },
      vitamin_a: { amount: 450, unit: "mcg RAE" },
      vitamin_d: { amount: 450, unit: "IU" },
      vitamin_e: { amount: 9.0, unit: "mg α-TE" },
      vitamin_k: { amount: 40, unit: "mcg" },
      vitamin_b1: { amount: 0.50, unit: "mg" },
      vitamin_b2: { amount: 0.80, unit: "mg" },
      vitamin_b6: { amount: 0.40, unit: "mg" },
      vitamin_b12: { amount: 1.6, unit: "mcg" },
      vitamin_c: { amount: 65, unit: "mg" },
      folate: { amount: 90, unit: "mcg DFE" },
      niacin: { amount: 3.8, unit: "mg NE" },
      calcium: { amount: 490, unit: "mg" },
      iron: { amount: 5.5, unit: "mg" },
      zinc: { amount: 4.2, unit: "mg" },
      magnesium: { amount: 42, unit: "mg" },
      iodine: { amount: 75, unit: "mcg" },
      selenium: { amount: 14, unit: "mcg" },
      copper: { amount: 350, unit: "mcg" },
      manganese: { amount: 45, unit: "mcg" },
      potassium: { amount: 510, unit: "mg" },
      sodium: { amount: 180, unit: "mg" },
      chloride: { amount: 360, unit: "mg" },
      phosphorus: { amount: 260, unit: "mg" },
    },
  },
  {
    name: "纽迪希亚 纽荃星壹加 儿童高能量配方粉 (1-10岁)",
    brand: "纽迪希亚/Nutricia",
    stage: 3,
    scoopWeightG: 5.0,
    waterPerScoopMl: 22.5,
    reconstitutionRatio: 0.200,
    servingSizeUnit: "per_100g",
    isActive: true,
    notes: "特殊医学用途儿童高能量全营养配方粉（1-10岁）。标准冲调4平勺(20g)兑90ml水，100ml提供100kcal，强化锌与B族维生素改善食欲，优质乳清蛋白与MCT促进吸收，助力幼儿及儿童追赶生长",
    nutrients: {
      energy_kcal: { amount: 500, unit: "kcal" },
      energy_kj: { amount: 2090, unit: "kJ" },
      protein: { amount: 16.0, unit: "g" },
      fat: { amount: 24.5, unit: "g" },
      carbohydrate: { amount: 54.0, unit: "g" },
      dha: { amount: 55, unit: "mg" },
      vitamin_a: { amount: 480, unit: "mcg RAE" },
      vitamin_d: { amount: 480, unit: "IU" },
      vitamin_c: { amount: 60, unit: "mg" },
      calcium: { amount: 580, unit: "mg" },
      iron: { amount: 6.0, unit: "mg" },
      zinc: { amount: 5.0, unit: "mg" },
      magnesium: { amount: 50, unit: "mg" },
      iodine: { amount: 80, unit: "mcg" },
      selenium: { amount: 16, unit: "mcg" },
      potassium: { amount: 550, unit: "mg" },
      sodium: { amount: 200, unit: "mg" },
      phosphorus: { amount: 320, unit: "mg" },
    },
  },
  {
    name: "纽迪希亚 纽太特 深度水解乳清蛋白配方粉 (0-12个月)",
    brand: "纽迪希亚/Nutricia",
    stage: 1,
    scoopWeightG: 4.5,
    waterPerScoopMl: 30.0,
    reconstitutionRatio: 0.130,
    servingSizeUnit: "per_100g",
    isActive: true,
    notes: "特殊医学用途深度水解乳清蛋白配方粉（0-12月龄）。100%短肽与游离氨基酸，无乳糖配方，针对牛奶蛋白中重度过敏及胃肠吸收不良",
    nutrients: {
      energy_kcal: { amount: 490, unit: "kcal" },
      protein: { amount: 11.5, unit: "g" },
      fat: { amount: 25.0, unit: "g" },
      carbohydrate: { amount: 55.0, unit: "g" },
      dha: { amount: 65, unit: "mg" },
      ara: { amount: 65, unit: "mg" },
      vitamin_a: { amount: 420, unit: "mcg RAE" },
      vitamin_d: { amount: 380, unit: "IU" },
      calcium: { amount: 390, unit: "mg" },
      iron: { amount: 5.0, unit: "mg" },
      zinc: { amount: 3.8, unit: "mg" },
    },
  },
  {
    name: "纽迪希亚 纽康特 氨基酸无敏婴儿配方粉 (0-12个月)",
    brand: "纽迪希亚/Nutricia",
    stage: 1,
    scoopWeightG: 4.6,
    waterPerScoopMl: 30.0,
    reconstitutionRatio: 0.133,
    servingSizeUnit: "per_100g",
    isActive: true,
    notes: "特殊医学用途婴儿氨基酸配方食品（0-12月龄）。100%游离氨基酸无敏配方，不含任何牛奶蛋白分子，针对重度牛奶蛋白过敏及多种食物过敏婴儿",
    nutrients: {
      energy_kcal: { amount: 485, unit: "kcal" },
      protein: { amount: 13.0, unit: "g" },
      fat: { amount: 24.0, unit: "g" },
      carbohydrate: { amount: 54.0, unit: "g" },
      dha: { amount: 70, unit: "mg" },
      ara: { amount: 70, unit: "mg" },
      vitamin_a: { amount: 430, unit: "mcg RAE" },
      vitamin_d: { amount: 390, unit: "IU" },
      calcium: { amount: 460, unit: "mg" },
      iron: { amount: 5.4, unit: "mg" },
      zinc: { amount: 4.0, unit: "mg" },
    },
  },
];

/**
 * 预置补剂产品库 (Presets)
 * 涵盖中国市场及海淘主流单方与复合营养补充剂（包含 Witsbb 健敏思全系列补剂）
 */
export const PRESET_SUPPLEMENT_PRODUCTS: Omit<SupplementProduct, "id" | "familyId" | "createdAt" | "updatedAt">[] = [
  // ==================== 1. 健敏思 Witsbb 补剂系列 ====================
  {
    name: "健敏思 (Witsbb) 婴儿液体维生素D3滴剂 (400IU无敏版)",
    brand: "Witsbb/健敏思",
    dosageForm: "drops",
    unitName: "滴",
    defaultDose: 1.0,
    isActive: true,
    notes: "每滴含维生素D3 400 IU (10mcg)，MCT无敏基底，无100+项常见过敏原，专为新生儿及敏宝设计",
    nutrients: {
      vitamin_d: { amount: 400, unit: "IU" },
    },
  },
  {
    name: "健敏思 (Witsbb) 儿童维生素D3滴剂 (600IU高阶版)",
    brand: "Witsbb/健敏思",
    dosageForm: "drops",
    unitName: "滴",
    defaultDose: 1.0,
    isActive: true,
    notes: "1岁以上幼儿及儿童适用。每滴含高浓度维生素D3 600 IU (15mcg)",
    nutrients: {
      vitamin_d: { amount: 600, unit: "IU" },
    },
  },
  {
    name: "健敏思 (Witsbb) 婴幼儿维生素AD软胶囊 (分龄温和型)",
    brand: "Witsbb/健敏思",
    dosageForm: "capsule",
    unitName: "粒",
    defaultDose: 1.0,
    isActive: true,
    notes: "每粒含维生素A 1500 IU (450 mcg RAE)，维生素D3 500 IU (12.5 mcg)，3:1黄金科学配比护眼强骨",
    nutrients: {
      vitamin_a: { amount: 450, unit: "mcg RAE" },
      vitamin_d: { amount: 500, unit: "IU" },
    },
  },
  {
    name: "健敏思 (Witsbb) 婴幼儿液体小蓝盒乳钙 (软胶囊型)",
    brand: "Witsbb/健敏思",
    dosageForm: "capsule",
    unitName: "粒",
    defaultDose: 1.0,
    isActive: true,
    notes: "每粒含天然优质乳钙 300mg，复配维生素D3 100 IU与维生素K2 5mcg，温和好吸收不便秘",
    nutrients: {
      calcium: { amount: 300, unit: "mg" },
      vitamin_d: { amount: 100, unit: "IU" },
      vitamin_k: { amount: 5, unit: "mcg" },
    },
  },
  {
    name: "健敏思 (Witsbb) 婴幼儿小金条液体有机钙 (柠檬酸苹果酸钙)",
    brand: "Witsbb/健敏思",
    dosageForm: "liquid_ml",
    unitName: "条",
    defaultDose: 1.0,
    isActive: true,
    notes: "每条(10ml)含微囊化有机柠檬酸苹果酸钙 200mg，维生素D3 200 IU，维生素K2 5mcg，酸甜水果味",
    nutrients: {
      calcium: { amount: 200, unit: "mg" },
      vitamin_d: { amount: 200, unit: "IU" },
      vitamin_k: { amount: 5, unit: "mcg" },
    },
  },
  {
    name: "健敏思 (Witsbb) 婴幼儿甘氨酸螯合铁滴剂 (温和高吸收)",
    brand: "Witsbb/健敏思",
    dosageForm: "liquid_ml",
    unitName: "ml",
    defaultDose: 1.0,
    isActive: true,
    notes: "每1ml含甘氨酸螯合铁 5.0mg，复配维生素C 15mg促吸收与维生素B族，温和不刺激肠胃无铁锈味",
    nutrients: {
      iron: { amount: 5.0, unit: "mg" },
      vitamin_c: { amount: 15.0, unit: "mg" },
      vitamin_b6: { amount: 0.5, unit: "mg" },
      vitamin_b12: { amount: 1.0, unit: "mcg" },
    },
  },
  {
    name: "健敏思 (Witsbb) 婴幼儿甘氨酸螯合锌滴剂 (葡萄味)",
    brand: "Witsbb/健敏思",
    dosageForm: "liquid_ml",
    unitName: "ml",
    defaultDose: 1.0,
    isActive: true,
    notes: "每1ml含高吸收螯合锌 3.5mg，复配维生素B6 0.6mg，葡萄果味宝宝接受度高",
    nutrients: {
      zinc: { amount: 3.5, unit: "mg" },
      vitamin_b6: { amount: 0.6, unit: "mg" },
    },
  },
  {
    name: "健敏思 (Witsbb) 婴幼儿高纯DHA藻油软胶囊 (小鱼型)",
    brand: "Witsbb/健敏思",
    dosageForm: "capsule",
    unitName: "粒",
    defaultDose: 1.0,
    isActive: true,
    notes: "每粒含纯净裂壶藻DHA 120mg (纯度40%+)，无腥味小鱼胶囊，不含EPA与重金属",
    nutrients: {
      dha: { amount: 120, unit: "mg" },
      vitamin_a: { amount: 100, unit: "mcg RAE" },
      vitamin_d: { amount: 100, unit: "IU" },
    },
  },
  {
    name: "健敏思 (Witsbb) 婴幼儿复合益生菌滴剂 (Bb-12 + LGG)",
    brand: "Witsbb/健敏思",
    dosageForm: "drops",
    unitName: "滴",
    defaultDose: 5.0,
    isActive: true,
    notes: "每5滴含双重明星菌株Bb-12与LGG 10亿CFU，复配维生素D3 200 IU，呵护娇嫩肠道",
    nutrients: {
      vitamin_d: { amount: 200, unit: "IU" },
    },
  },

  // ==================== 2. 经典国药与海外主流补剂 ====================
  {
    name: "星鲨 维生素D3滴剂 (软胶囊型)",
    brand: "星鲨",
    dosageForm: "capsule",
    unitName: "粒",
    defaultDose: 1.0,
    isActive: true,
    notes: "每粒含维生素D3 400 IU (10微克)，经典国药准字",
    nutrients: {
      vitamin_d: { amount: 400, unit: "IU" },
    },
  },
  {
    name: "Ddrops 婴儿天然维生素D3滴剂",
    brand: "Ddrops",
    dosageForm: "drops",
    unitName: "滴",
    defaultDose: 1.0,
    isActive: true,
    notes: "每滴含维生素D3 400 IU，天然羊毛脂提取",
    nutrients: {
      vitamin_d: { amount: 400, unit: "IU" },
    },
  },
  {
    name: "伊可新 维生素AD滴剂 (绿葫芦 0-1岁)",
    brand: "达因/伊可新",
    dosageForm: "capsule",
    unitName: "粒",
    defaultDose: 1.0,
    isActive: true,
    notes: "0-1岁婴儿适用。每粒含维生素A 1500 IU (450 mcg RAE)，维生素D3 500 IU (12.5 mcg)",
    nutrients: {
      vitamin_a: { amount: 450, unit: "mcg RAE" },
      vitamin_d: { amount: 500, unit: "IU" },
    },
  },
  {
    name: "伊可新 维生素AD滴剂 (粉葫芦 1岁以上)",
    brand: "达因/伊可新",
    dosageForm: "capsule",
    unitName: "粒",
    defaultDose: 1.0,
    isActive: true,
    notes: "1岁以上幼儿适用。每粒含维生素A 2000 IU (600 mcg RAE)，维生素D3 700 IU (17.5 mcg)",
    nutrients: {
      vitamin_a: { amount: 600, unit: "mcg RAE" },
      vitamin_d: { amount: 700, unit: "IU" },
    },
  },
  {
    name: "Ostelin 婴幼儿液体乳钙 (含维生素D3+K2)",
    brand: "Ostelin/奥斯特林",
    dosageForm: "liquid_ml",
    unitName: "ml",
    defaultDose: 1.0,
    isActive: true,
    notes: "每1ml含钙 100mg，维生素D3 200 IU (5 mcg)，维生素K2 5 mcg。复合补钙补D",
    nutrients: {
      calcium: { amount: 100, unit: "mg" },
      vitamin_d: { amount: 200, unit: "IU" },
      vitamin_k: { amount: 5, unit: "mcg" },
    },
  },
  {
    name: "童年时光 (ChildLife) 婴幼儿液体钙镁锌滴剂",
    brand: "ChildLife",
    dosageForm: "liquid_ml",
    unitName: "ml",
    defaultDose: 5.0,
    isActive: true,
    notes: "每5ml含钙 84mg，镁 38mg，锌 0.67mg，维生素D3 33 IU",
    nutrients: {
      calcium: { amount: 84, unit: "mg" },
      magnesium: { amount: 38, unit: "mg" },
      zinc: { amount: 0.67, unit: "mg" },
      vitamin_d: { amount: 33, unit: "IU" },
    },
  },
  {
    name: "艾瑞可 (Eric Favre) 婴幼儿液体铁滴剂",
    brand: "Eric Favre/艾瑞可",
    dosageForm: "liquid_ml",
    unitName: "ml",
    defaultDose: 1.0,
    isActive: true,
    notes: "每1ml含铁 7mg，并复配维生素B群 (B1 0.55mg, B2 0.7mg, B6 0.7mg, B12 1.25mcg)",
    nutrients: {
      iron: { amount: 7.0, unit: "mg" },
      vitamin_b1: { amount: 0.55, unit: "mg" },
      vitamin_b2: { amount: 0.7, unit: "mg" },
      vitamin_b6: { amount: 0.7, unit: "mg" },
      vitamin_b12: { amount: 1.25, unit: "mcg" },
    },
  },
  {
    name: "艾瑞可 (Eric Favre) 婴幼儿液体锌滴剂",
    brand: "Eric Favre/艾瑞可",
    dosageForm: "liquid_ml",
    unitName: "ml",
    defaultDose: 1.0,
    isActive: true,
    notes: "每1ml含锌 3mg，维生素B6 0.7mg",
    nutrients: {
      zinc: { amount: 3.0, unit: "mg" },
      vitamin_b6: { amount: 0.7, unit: "mg" },
    },
  },
  {
    name: "纽曼思 (Nemans) 婴幼儿DHA藻油软胶囊",
    brand: "Nemans/纽曼思",
    dosageForm: "capsule",
    unitName: "粒",
    defaultDose: 1.0,
    isActive: true,
    notes: "每粒含高纯度裂壶藻DHA 100mg，无重金属污染",
    nutrients: {
      dha: { amount: 100, unit: "mg" },
    },
  },
  {
    name: "拜奥 (BioGaia) 罗伊氏乳杆菌益生菌滴剂 (含维D版)",
    brand: "BioGaia/拜奥",
    dosageForm: "drops",
    unitName: "滴",
    defaultDose: 5.0,
    isActive: true,
    notes: "每5滴含罗伊氏乳杆菌 1亿CFU + 维生素D3 400 IU",
    nutrients: {
      vitamin_d: { amount: 400, unit: "IU" },
    },
  },
];

