import booksDataset from "../../data/05_books.json";
import foodsDataset from "../../data/04_foods.json";

/**
 * The legacy golden fixture makes Prisma's generated reference-row IDs
 * reproducible with this UUIDv5 name.  The row index is derived from the
 * checked-in source array, rather than from a golden response or a fixed row
 * UUID.  Keep this compatibility detail in the Web adapter; canonical API
 * resources continue to expose their natural IDs.
 */
const LEGACY_UUID_NAMESPACE = "6ba7b811-9dad-11d1-80b4-00c04fd430c8";
const LEGACY_UUID_PREFIX = "growdesk-test-golden";

type BookSource = { id?: unknown };
type FeedingGuidelineSource = { ageMinMonths?: unknown; ageMaxMonths?: unknown };

const books = (booksDataset.books as BookSource[]);
const feedingGuidelines = (foodsDataset.feedingGuidelines as FeedingGuidelineSource[]);

function uuidBytes(value: string): Uint8Array {
  const normalized = value.replace(/-/g, "");
  if (!/^[0-9a-f]{32}$/i.test(normalized)) throw new Error(`Invalid UUID: ${value}`);
  const bytes = new Uint8Array(16);
  for (let index = 0; index < bytes.length; index += 1) {
    bytes[index] = Number.parseInt(normalized.slice(index * 2, index * 2 + 2), 16);
  }
  return bytes;
}

function sha1(bytes: Uint8Array): Uint8Array {
  // This is the SHA-1 compression function required by RFC 4122 UUIDv5.
  // The adapter runs in the Next.js Node runtime, where TextEncoder is
  // available without making the old API projection asynchronous.
  const bitLength = bytes.length * 8;
  const paddedLength = ((bytes.length + 9 + 63) >> 6) << 6;
  const padded = new Uint8Array(paddedLength);
  padded.set(bytes);
  padded[bytes.length] = 0x80;
  const view = new DataView(padded.buffer);
  view.setUint32(padded.length - 4, bitLength >>> 0, false);

  let h0 = 0x67452301;
  let h1 = 0xefcdab89;
  let h2 = 0x98badcfe;
  let h3 = 0x10325476;
  let h4 = 0xc3d2e1f0;

  for (let offset = 0; offset < padded.length; offset += 64) {
    const words = new Uint32Array(80);
    for (let index = 0; index < 16; index += 1) {
      words[index] = view.getUint32(offset + index * 4, false);
    }
    for (let index = 16; index < 80; index += 1) {
      const value = words[index - 3] ^ words[index - 8] ^ words[index - 14] ^ words[index - 16];
      words[index] = (value << 1) | (value >>> 31);
    }

    let a = h0;
    let b = h1;
    let c = h2;
    let d = h3;
    let e = h4;
    for (let index = 0; index < 80; index += 1) {
      let functionValue: number;
      let constant: number;
      if (index < 20) {
        functionValue = (b & c) | (~b & d);
        constant = 0x5a827999;
      } else if (index < 40) {
        functionValue = b ^ c ^ d;
        constant = 0x6ed9eba1;
      } else if (index < 60) {
        functionValue = (b & c) | (b & d) | (c & d);
        constant = 0x8f1bbcdc;
      } else {
        functionValue = b ^ c ^ d;
        constant = 0xca62c1d6;
      }
      const rotated = (a << 5) | (a >>> 27);
      const next = (rotated + functionValue + e + constant + words[index]) | 0;
      e = d;
      d = c;
      c = (b << 30) | (b >>> 2);
      b = a;
      a = next;
    }
    h0 = (h0 + a) | 0;
    h1 = (h1 + b) | 0;
    h2 = (h2 + c) | 0;
    h3 = (h3 + d) | 0;
    h4 = (h4 + e) | 0;
  }

  const digest = new Uint8Array(20);
  const output = new DataView(digest.buffer);
  [h0, h1, h2, h3, h4].forEach((value, index) => output.setUint32(index * 4, value >>> 0, false));
  return digest;
}

function formatUuid(bytes: Uint8Array): string {
  const hex = [...bytes].map(value => value.toString(16).padStart(2, "0")).join("");
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
}

/** Reproduce the row ID generated by legacy-golden-reference-fixture.py. */
export function legacyReferenceId(table: string, index: number): string {
  if (!Number.isInteger(index) || index < 0) throw new Error(`Invalid legacy row index: ${index}`);
  const namespace = uuidBytes(LEGACY_UUID_NAMESPACE);
  const name = new TextEncoder().encode(`${LEGACY_UUID_PREFIX}/${table}/${index}`);
  const input = new Uint8Array(namespace.length + name.length);
  input.set(namespace);
  input.set(name, namespace.length);
  const digest = sha1(input).slice(0, 16);
  digest[6] = (digest[6] & 0x0f) | 0x50;
  digest[8] = (digest[8] & 0x3f) | 0x80;
  return formatUuid(digest);
}

function sourceId(value: unknown): string | undefined {
  return typeof value === "string" && value.length > 0 ? value : undefined;
}

function sourceNumber(value: unknown): number | undefined {
  return typeof value === "number" && Number.isFinite(value) ? value : undefined;
}

function bookSourceIndex(book: Record<string, unknown>): number {
  const key = sourceId(book.bookId) ?? sourceId(book.id);
  return books.findIndex(candidate => sourceId(candidate.id) === key);
}

export function legacyBookId(book: Record<string, unknown>): string | undefined {
  const index = bookSourceIndex(book);
  return index >= 0 ? legacyReferenceId("Book", index) : undefined;
}

/** Resolve a legacy list/detail path ID back to the canonical natural ID. */
export function canonicalBookId(value: string): string | undefined {
  const index = books.findIndex(candidate => sourceId(candidate.id) === value);
  if (index >= 0) return sourceId(books[index].id);
  const legacyIndex = books.findIndex((_candidate, candidateIndex) => legacyReferenceId("Book", candidateIndex) === value);
  return legacyIndex >= 0 ? sourceId(books[legacyIndex].id) : undefined;
}

export function legacyFeedingGuidelineId(item: Record<string, unknown>): string | undefined {
  const min = sourceNumber(item.ageMinMonths);
  const max = sourceNumber(item.ageMaxMonths);
  const index = feedingGuidelines.findIndex(candidate =>
    sourceNumber(candidate.ageMinMonths) === min && sourceNumber(candidate.ageMaxMonths) === max,
  );
  return index >= 0 ? legacyReferenceId("FeedingGuideline", index) : undefined;
}
